### ISSUE TITLE
make a Jobs section

### ISSUE THREAD

**Issue by kelle** [astropy/astropy.github.com#512]
We need a place to advertise job openings.

**Comment by kelle** [comment]
I think we should have astropy.org/jobs which has a bulleted lists of openings. And then single links for specific jobs.  E.g., astrop.org/jobs/community-mgr-2023.html

**Comment by pllim** [comment]
Shouldn't we advertise to existing job boards (like the AAS job register) instead of trying to maintain our own platform?

**Comment by kelle** [comment]
Job listings disappear from the AAS Job Register once you stop paying.  I think having astropy.org as the primary place where we put our ads is best.  We can post links to these pages from all the job boards we decide to post to.

**Comment by sunidhisachan** [comment]
hey @kelle , I would like to take this up. Can you provide me with the links of jobs ?

**Comment by kelle** [comment]
We don't have any job listings at the moment but maybe you can work on a pull request using any job listing. Maybe just use this one as a template: https://jobregister.aas.org/ad/13bec552

**Comment by sunidhisachan** [comment]
Thanks for the link , I will be looking at it soon.

**Comment by sunidhisachan** [comment]
hey @kelle 
Here is the design of the site which I have implemented. Please let me know if this works fine for you.
Also I was wondering about read more section.
shall we provide external job links to another platform?
shall we make it in a way that on clicking it would open a new job page within the site?
Please , do let me know what should I go ahead with.

![Screenshot from 2023-02-23 02-25-01](https://user-images.githubusercontent.com/86006420/220757181-04f15fc3-9972-4fe0-b891-d07be744f32d.png)

**Comment by kelle** [comment]
Hmm, we already have an existing site and this layout doesn't seem to "match" our current site. Have you looked at the code in this repo and our site here: https://www.astropy.org/?

What I meant above by use as "template", what I meant is just the text of the job ad, not the website design.

**Comment by kelle** [comment]
Found out NumFocus has a jobs board setup: http://jobs.numfocus.org

So maybe we don't set up a page but instead link to that board. 

Still not sure where we should put those links. Probably the home page to get max visibility?
